# Generated by Django 3.1.4 on 2021-03-02 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userconfig',
            old_name='user',
            new_name='username',
        ),
    ]
