# Generated by Django 3.1.4 on 2021-03-04 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210304_1317'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userconfig',
            old_name='username',
            new_name='useremail',
        ),
    ]
