# Generated by Django 3.1.4 on 2021-03-04 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210304_1329'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userconfig',
            old_name='useraccount',
            new_name='user_account',
        ),
    ]
