# Generated by Django 3.1.4 on 2021-03-06 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('api', '0006_auto_20210304_1333'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserConfigModel',
            fields=[
                ('user_account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='account.account')),
                ('news_app', models.BooleanField()),
                ('covid_tracker', models.BooleanField()),
                ('traffic_status', models.BooleanField()),
                ('weather_app', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='UserImageModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.DeleteModel(
            name='UserConfig',
        ),
    ]
