# Generated by Django 3.1.4 on 2021-03-06 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20210306_1352'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserImageModel',
        ),
    ]
