# Generated by Django 3.1.4 on 2021-03-06 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('api', '0008_delete_userimagemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserImageModel',
            fields=[
                ('user_account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='account.account')),
            ],
        ),
    ]
