# Generated by Django 3.1.4 on 2021-03-06 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_userimagemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='userimagemodel',
            name='user_image',
            field=models.ImageField(default='/assets/unknown_user.png', upload_to='user_images/'),
        ),
    ]
